Update makeplots
KamitaniLab/bdpy pull request #95
Opened 2024-09-09 07:37 UTC by micchu

makeplots2 をアップロードしました．

- plotのサブ関数群を更新
    - 現在ほぼ使用されていないと見られる __plot_paired_violin, __plot_swarm, __plot_box を削除
    - 代わりに新たに __plot_line を追加
    - __plot_bar を seaborn を使用する記述に変更
    - 全てのplotサブ関数について，dataframeでデータを引き取るように修正し，legend_handlerを返り値に持つようにインタフェースを共通化
    - plotサブ関数ごとに配色のルールがバラバラだったのを共通化
- makeplots2 本体を更新
    - 個々の plot のサブ関数に依存する引数は makeplots_kws で引き取るように変更
        - これにより以前とmakeplotsのインタフェースが変わるため，makeplots ではなく makeplots2 という名前の関数として追加した次第
    - 全ての plot サブ関数に dataframe を渡すように更新
    - __strict_data と __weird_form_to_long のみを使用することになり，__get_data は対象データがなくなったため削除
    - legend の処理が plot_type によって異なっていたのを一本化
    - plot_type="original" を追加し，plot_func の引数独自のplotサブ関数を渡せるように変更

2024-09-09 14:43 UTC, ShuntaroAoki requested changes

2024-09-09 14:43 UTC, ShuntaroAoki commented on bdpy/fig/makeplots2.py
> +    plot_type : {'violin', 'swarm+box', 'bar', 'line', 'original'}
'original' は意味が伝わらないのでより適切な名前にできませんか。
または、plot_type を廃止し、violin プロットなども predefined な関数を plot_func に渡すようにしてもよいです。

2024-09-10 02:02 UTC, micchu commented on bdpy/fig/makeplots2.py
> +    plot_type : {'violin', 'swarm+box', 'bar', 'line', 'original'}
> または、plot_type を廃止し、violin プロットなども predefined な関数を plot_func に渡すようにしてもよいです。
それをすると，__sub_* とかの呼び出しのために，新たにimport文を書かなければならなくて，手間が増えるので嫌です．定型なグラフは単純に呼び出せるようにしたいです．

plot_typeがなしで，plot_funcがある場合に，plot_funcが実行されるという流れはいかがでしょうか？

2024-09-10 04:29 UTC, ShuntaroAoki commented on bdpy/fig/makeplots2.py
> +    plot_type : {'violin', 'swarm+box', 'bar', 'line', 'original'}
>plot_typeがなしで，plot_funcがある場合に，plot_funcが実行されるという流れはいかがでしょうか？

それは複雑すぎるかなと思います。

別の方法として、`plot_type` を `str | Callable` として、`'violin', 'swarm+box', 'bar', 'line'` のいずれかならそのプロットを、関数が渡されたときはその関数でプロットする、というのでどうでしょうか。
この場合、`plot_type` という名前はあまり適切ではないので、単に `plot` としたほうがよいと思います。

2024-09-10 04:43 UTC, micchu commented on bdpy/fig/makeplots2.py
> +    plot_type : {'violin', 'swarm+box', 'bar', 'line', 'original'}
なるほど，そちらでいきましょう．

2024-09-10 06:59 UTC, micchu commented on bdpy/fig/makeplots2.py
> +    plot_type : {'violin', 'swarm+box', 'bar', 'line', 'original'}
plot_typeとplot_funcをplotで一元化して扱うようにしました．
あと他にも，
1. color_paletteでwarningが出ていたところの修正
2. violin plotでデータが欠損している条件にdummyデータ([np.nan, np.nan])を入力するところ
について変更しました．

2024-09-11 04:59 UTC, ShuntaroAoki approved these changes

2024-09-11 05:00 UTC, merged